### ISSUE TITLE
[FATAL]  no known snapshots

### ISSUE THREAD

**Issue by wendaoshuangyue** [confluentinc/bottledwater-pg#149]
My bottledwater suddenly crashed with following error message and no long able to restart. Can anyone help me? Thanks a lot.
Error message:
[FATAL] Replication stream was unexpectedly terminated: Error:  no known snapshots
CONTEXT:  slot "bottledwater_hpg_000000", output plugin "bottledwater", callback in change, related LSN address is 0/2C833598

**Comment by igouss** [comment]
I see same error in  "wal2json"

org.postgresql.util.PSQLException: ERROR: no known snapshots
  Where: slot "cdc", output plugin "wal2json", in the change callback, associated LSN CC/88421640
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
	at org.postgresql.core.v3.QueryExecutorImpl.processCopyResults(QueryExecutorImpl.java:1107)
	at org.postgresql.core.v3.QueryExecutorImpl.endCopy(QueryExecutorImpl.java:956)
	at org.postgresql.core.v3.CopyDualImpl.endCopy(CopyDualImpl.java:27)
	at org.postgresql.core.v3.replication.V3PGReplicationStream.close(V3PGReplicationStream.java:278)
